---
name: Test
on: pull_request
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # To update pull requests
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: ./
