---
name: Test
on: pull_request
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # To update pull requests
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./
